### ISSUE TITLE
Not clear in this scenario how we would handle separate rolling out processes.

### ISSUE THREAD

**Issue by kirill-baryshnikov** [rzetelskik/distributed-linters#14]
https://github.com/rzetelskik/distributed-linters/blob/efc278adae572a87eb02a9dedf6e543238940e7e/manager/manager.go#L36

Could you please elaborate - how we will handle rollouts that are going at the same time:
e.g. 0.1% version 2.1
10% version 2.0
other - version 1.0

**Comment by tosum** [comment]
When new version arrives the it takes over the rollout - new version is more important so it gets a larger and larger share of the workers.
