### ISSUE TITLE
Kindly ask to put ratio constants as the array (0.1%, 1%, 10%, 50%, 100%).

### ISSUE THREAD

**Issue by kirill-baryshnikov** [rzetelskik/distributed-linters#21]
https://github.com/rzetelskik/distributed-linters/blob/efc278adae572a87eb02a9dedf6e543238940e7e/manager/manager.go#L176

So the update happens gradually and we can ensure before moving to the next ratio that all systems operate correctly and we don't need to rollback the version.

**Comment by tosum** [comment]
Putting them in an array looks like a needles complication. We would need to track at which index we are at the moment and cautiously manipulate it. Right now we just need to multiply the current ratio by a constant, which is a simple and robust solution.

> So the update happens gradually and we can ensure before moving to the next ratio that all systems operate correctly and we don't need to rollback the version.

This functionality is implemented in the current code.
