### ISSUE TITLE
Please extract localhost constant to top of the file so we can easily switch to the distributed model when the workers are on different machine

### ISSUE THREAD

**Issue by kirill-baryshnikov** [rzetelskik/distributed-linters#24]
https://github.com/rzetelskik/distributed-linters/blob/efc278adae572a87eb02a9dedf6e543238940e7e/manager/manager.go#L256

**Comment by tosum** [comment]
If we were to expand it to multiple machines there would be many more changes in the startup logic that need to be done, I don't see how making the localhost a constant would help in any way.
