### ISSUE TITLE
?? Not clear return statement. Why do we return nil as an error in case of false? How the user can see linter messages and recommendations?

### ISSUE THREAD

**Issue by kirill-baryshnikov** [rzetelskik/distributed-linters#32]
https://github.com/rzetelskik/distributed-linters/blob/efc278adae572a87eb02a9dedf6e543238940e7e/manager/manager.go#L304

**Comment by tosum** [comment]
Task specification only required us to return `true` or `false`, I'd prefer to stay within the original requirements.
