### ISSUE TITLE
Suggest to split into 2 endpoints: add_worker and delete_worker. As for now one endpoint performs 2 different functions

### ISSUE THREAD

**Issue by kirill-baryshnikov** [rzetelskik/distributed-linters#36]
https://github.com/rzetelskik/distributed-linters/blob/efc278adae572a87eb02a9dedf6e543238940e7e/manager/manager.go#L365

**Comment by tosum** [comment]
We followed the design described in the original design doc.
Workers are a resource that can be manipulated using various HTTP request types.
